# -------------------------------
# Basic configs
# -------------------------------
TOP       = fibonacci
BUILDDIR  = build

# -------------------------------
# Sources
# -------------------------------
SRCS      = rtl/*.sv
TB        = tb/tb_$(TOP).sv
LPF 	  = fpga/$(TOP).lpf

include ../../colorlight-i9-examples/rules.mk
