# -------------------------------
# Basic configs
# -------------------------------
TOP       = traffic_light
BUILDDIR  = build

# -------------------------------
# Sources
# -------------------------------
SRCS      = rtl/*.sv
TB        = tb/tb_$(TOP).sv
LPF 	  = fpga/$(TOP).lpf

include ../rules.mk
